Bump Pytest from 5.0 to 7.2.0; Run poetry update
Without `poetry update`, Pytest fails with:

```
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 896, in find_distributions
    found = cls._search_paths(context.name, context.path)
AttributeError: 'str' object has no attribute 'name'
```

After `poetry update`, with Pytest 5.0 in Python 3.10 environment,
Pytest fails with:

```
.venv/lib/python3.10/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:143: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:330: in _rewrite_test
    co = compile(tree, fn, "exec", dont_inherit=True)
E   TypeError: required field "lineno" missing from alias
```

With both `poetry update` and Pytest 7.2.0, both these errors are fixed.